### ISSUE TITLE
How to visualise scores

### ISSUE THREAD

**Issue by FritzPeleke** [kundajelab/deeplift#106]
Hi, so I am trying to use Deeplift to visualise which area of a sequence is more important for prediction.
As reference I used the dinucleotide shuffled sequence for each normal sequence.
After calculating the score, I do not know how to visualise it. 
This work was done by some authors and they used np.average(scores, axis=0), where as here on the Deeplift GitHub np.sum(scores, axis=2) is suggested. 

I will love to be able to obtain a plot that can show me which parts of the sequences were key in prediction. 
Here is a link to my code
https://github.com/FritzPeleke/Pseudogene_model_on_Zmays/blob/master/DeepLIFT.py

Thanks

**Comment by AvantiShri** [comment]
Hi @FritzPeleke, what are the dimensions of the sequence input to your model? From glancing at your code, it looks like your one-hot encoded array has four dimensions. What does each dimension represent?

For context, in the example notebook, the one-hot encoded arrays have three dimensions, and it is the last dimension that is the ACGT axis; that is why we do np.sum(scores, axis=2); we sum the scores across ACGT at each position to get the total importance of each position.

**Comment by FritzPeleke** [comment]
Hi @AvantiShri the shape of each input will be (4, 3000, 1). I think I might have an idea as to why the authors did what they did. When we expand dimensions with Numpy we have four dimensions (number of sequences, number of nucleotide, length of sequence, the new dimension). This is just like the (batch_size, height, width, depth).

Assuming my dataset had just 2 sequences in it, the shape of the scores will be (2, 4, 3000, 1).
So the average first by axis=0, which is typically like averaging all As, Gs, Cs and Ts. That will give a new shape of (1, 4, 3000, 1). Then they did np.squeeze to transform the array to (1, 4, 3000).
 Then did a final np.average(transformed_array, axis=0). This produces a shape of (1, 3000) such that each nucleotide in the sequence has a contribution score.
From what I understand now. I think that was their move.
