### ISSUE TITLE
Possibility to obtain intermediate multipliers?

### ISSUE THREAD

**Issue by CingisAlexander** [kundajelab/deeplift#107]
Dear Avanti,

I would like to ask if it is possible to obtain through the DeepLIFT API also intermediate multipliers? So, suppose a neural network with two hidden layers h1, h2. Can I obtain multipliers coming from the first neuron in h1 and going to all other neurons in h2, i.e. these types of multipliers m_{h1_1,h2_1}, m_{h1_1,h2_2}, … ? 

Thank you very much for your Time
Cingis

**Comment by AvantiShri** [comment]
Hi Cingis, sorry for the delay in responding. Yes, it is possible to obtain intermediate multipliers; in your example, you would set the hidden layer h2 to be the "target layer" and hidden layer h1 to be the "find scores" layer. If you then then specify individual neurons in h2 using the "task_idx" argument, the contributions of the every neuron in h1 to the specified neuron in h2 would be computed. However, you would have to repeat this for each individual neuron in h2 (by changing the "task_idx" argument), which may end up being slow. But at the end of it, you would end up with the contributions of every neuron in h1 to every neuron in h2. Does that make sense?

By the way, for the simple case of the multipliers between hidden layer h1 and hidden layer h2 (where h2 presumably comes right after h1), it may be easier to directly calculate what the multipliers would be yourself, without going through my implementation - specifically, the multipliers for a linear matrix multiplication would just be given by the weights, and those multipliers would be adjusted depending on the nonlinearity used in h2. However, if your real use-case involves multiple intermediate hidden layers, it might be harder.

**Comment by CingisAlexander** [comment]
Dear Avanti,

Thank you very much for your time and answer! Your answer has helped me 😊

I am closing this issue

Kind Regards
Cignis
