### ISSUE TITLE
Question regarding version 0.6.11.0 that is not anymore available.

### ISSUE THREAD

**Issue by CingisAlexander** [kundajelab/deeplift#120]
Dear Avanti,

I am using the version 0.6.11.0 of your DeepLIFT implementation to compute the non-linear rescale rule. Unfortunately, the version is not anymore in your repository available. Therefore, I would like to ask which of the current available versions is the most appropriate to replace the version 0.6.11.0?

Thank you

**Comment by AvantiShri** [comment]
Hi, either of the later versions works well - go ahead and use 0.6.13.0!

**Comment by CingisAlexander** [comment]
Dear Avanti,
perfect, thank you.
