### ISSUE TITLE
how do I download deeplift version of 0.5.1-theano

### ISSUE THREAD

**Issue by NicoleKenn** [kundajelab/deeplift#125]
A code program need to be run with deeplift version of 0.5.1-theano. But there is an error:  File "setup.py" or "setup.cfg" not found.
how do i download this old version? thanks!

**Comment by AvantiShri** [comment]
Can you try:
```
git clone https://github.com/kundajelab/deeplift.git
cd deeplift
git checkout v0.5.1-theano
pip install .
```
