### ISSUE TITLE
Broken dependencies - `blobs/__init__.py`

### ISSUE THREAD

**Issue by jisungk** [kundajelab/deeplift#14]
In the `master` branch, `blobs/__init__.py` tries to import `blobs.maxout` and `blobs.rnn` modules which do not currently exist (they did in previous commits). This causes import errors.

I'm not sure if the `blobs.maxout` and `blobs.rnn` modules have become redundant, but deleting the import statements in `blobs/__init__.py` allows the MNIST example to run without import errors. 

See https://github.com/kundajelab/deeplift/blob/master/deeplift/blobs/__init__.py

**Comment by AvantiShri** [comment]
Thanks for catching this; those modules exist on a private dev branch and the import statements + cached modules lingered when I merged into the private branch. I will set up continuous integration eventually to avoid introducing this in the future.
