### ISSUE TITLE
New, unknown printing behavior

### ISSUE THREAD

**Issue by jisungk** [kundajelab/deeplift#15]
When I run the MNIST example, a bunch of "twos" are printed:

<img width="565" alt="screen shot 2017-03-06 at 10 16 32 pm" src="https://cloud.githubusercontent.com/assets/9053987/23640370/23d63354-02bb-11e7-865c-48f64de29ede.png">

This seems undesirable for users. 

Note: I had to temporarily fix issue #14 (deleting some imports in `blobs/__init__.py`) to get the MNIST example running. However, it seems unlikely that this is the problem.

**Comment by AvantiShri** [comment]
Thanks for catching this, just pushed a fix.
