### ISSUE TITLE
Which version of keras should be used? 

### ISSUE THREAD

**Issue by KirillTim** [kundajelab/deeplift#18]
I have newest keras version installed `Keras (2.0.1)` and `Theano (0.8.2)` (while deeplift depend on theano >0.8)
No wonder, I have runtime exceptions about API mismatch:
```
 .....
/home/kirill/Desktop/deeplift/deeplift/conversion/keras_conversion.py in layer_name_to_conversion_function(layer_name)
    335     # lowercase to create resistance to capitalization changes
    336     # was a problem with previous Keras versions
--> 337     return name_dict[layer_name.lower()]
    338 
    339 

KeyError: 'conv1d'
```
I have very little experience with Keras and it seems that I can't fix this bug by myself :(
I think that easiest solution would be to add specific(no matter how old) Keras version to dependencies. 
Could you, please, do it?

**Comment by KirillTim** [comment]
OMG, my bad.
 I overlooked `The original implementation of DeepLIFT uses a theano backend, but an alpha version of the tensorflow implementation (developed using tensorflow 0.12.0rc and Keras 1.1.2)` line in README.md

**Comment by AvantiShri** [comment]
The README was written before Keras 2.0 was a thing, so it does need to be updated. Please let me know if you have any issues using Keras 1.x
