### ISSUE TITLE
tensorflow branch lacks json model design parameter

### ISSUE THREAD

**Issue by krrome** [kundajelab/deeplift#19]
Hi,
it seems like that the tensorflow branch lacks the json parameter option for deeplift.conversion.keras_conversion.load_keras_model, which is present in the master branch. Using the function as it is implemented in the master branch worked for me also for tensorflow.

**Comment by AvantiShri** [comment]
Thanks a lot for bringing this to my attention; I will include the json parameter in an upcoming update.

**Comment by AvantiShri** [comment]
Big update coming soon but in the meantime I pushed a fix to the tensorflow branch with the adjustment. Thanks again!
