### ISSUE TITLE
problem with the normalize weights function for convolution layer in tensorflow branch 

### ISSUE THREAD

**Issue by satroz** [kundajelab/deeplift#20]
Hello, 

I was trying to use the function `mean_normalise_first_conv_layer_weights` in the `keras.conversion` for my model built with the tensorflow backend.  However I kept getting the following error:

`File "/home/Programs/deeplift/deeplift/util.py", line 132, in mean_normalise_weights_for_sequence_convolution
    assert weights.shape[1]==1, weights.shape`
AssertionError: (4, 10, 1, 45)

My guess is that this method hasn't been converted from the theano to the tensorflow expected 
layer weight shapes?

**Comment by AvantiShri** [comment]
Yes that is very likely the problem. I can update that, thanks for pointing it out.

**Comment by AvantiShri** [comment]
Hi @satroz, do you mind letting me know how soon you need this? I am planning a significant update to deeplift in the next week or so (which will be accompanied by a new arXiv preprint), and I would ideally like to bundle this in with the update. However, if you need it soon, let me know and I will prioritize that.

**Comment by satroz** [comment]
Thanks ! Yeah no worries, I guess I can wait another week or two for the big update.... but if you think it'll take longer than that then would be nice to have it sooner then ;)

**Comment by AvantiShri** [comment]
Hey @satroz, big update coming soon (need to get approval from my adviser to release it) but in the mean time I just pushed an update to the current tensorflow branch that lets you specify the axis of normalisation. I tested it out on a model with tensorflow ordering (weights of first conv layer had shape 4x<filter width>x1x<num output channels>) and it seems to work - you can view the notebook with the test here: https://github.com/AvantiShri/model_storage/blob/4143cfce7e61611d4c42984578e420cd7556c4b6/deeplift/genomics/test_mean_normalise_weights.ipynb

Let me know if you run into any trouble. I am hoping to push the big update out by Tuesday, pending a green light.
