### ISSUE TITLE
KeyError: 'inputlayer'?

### ISSUE THREAD

**Issue by boxiangliu** [kundajelab/deeplift#25]
Hi Avanti,

I am getting a pretty obscure error as follows: 

KeyError: 'inputlayer'

There is no more message after that. 

I used the keras functional API to build my model, which contains two inputs. Could it be that none of my inputs is named "inputlayer"? 

Bosh

**Comment by AvantiShri** [comment]
Hi Bosh, that's surprising; input layer conversion should be handled by this line, which just checks the type of the layer: https://github.com/kundajelab/deeplift/blob/master/deeplift/conversion/keras_conversion.py#L522

Can you send me the architecture/saved model? Is the error thrown by this line? https://github.com/kundajelab/deeplift/blob/master/deeplift/conversion/keras_conversion.py#L331

**Comment by AvantiShri** [comment]
Resolved; model was a functional model and not a sequential model. Functional models can be converted with keras_conversion.convert_functional_model(...)
