### ISSUE TITLE
License and clarification on using baremetal TF models?

### ISSUE THREAD

**Issue by adebayoj** [kundajelab/deeplift#35]
Hi, 

I have two questions. What license is deeplift under? I am guessing MIT license? I looked around but couldn't quite track the license down. 

2) I have some models in tensorflow that I have trained and would like to use deeplift to 'interpret', is this best to just import that weights into keras and interpret the keras version? Is there a straightforward way to this or am I missing something. 

Thanks!

**Comment by AvantiShri** [comment]
Sorry that I never replied to this. I have been navigating some health issues over the past year, but I am better now and have been more active in maintaining the repo. In case you are still interested in the answers to your questions: the license is the open MIT license (I have updated the repo to reflect this), and yes, converting to a Keras model would be the easiest way to go.
