### ISSUE TITLE
TAL-GATA example: KeyError: 'class_name' when loading Keras model

### ISSUE THREAD

**Issue by Pandaman-Ryan** [kundajelab/deeplift#4]
Hi,

I am learning how to use deeplift by trying the TAL-GATA example you provided. But unfortunately, when loading your keras model, I met : "KeyError: 'class_name'

I am using Keras 1.1.1 version with Theano as the backend. So I guess this error is caused by format of yaml changed in Keras 1.X.

Could you please upload a separate model data generated using Keras 1.X, or could you please share the code you used for model constructing and training?

Thank you so much!

**Comment by AvantiShri** [comment]
Hi Pandaman-Ryan,

I can retrain the model using Keras 1.1.1, but I would also have to update DeepLIFT to support autoconversion of Keras 1.1.1 models. I will put this on my todo list and update this thread when I have Keras 1.1.1 compatibility. In the meantime, you might consider temporarily installing keras 0.3 using the following command: `pip install -e git://github.com/fchollet/keras.git@0.3.3#egg=keras`

**Comment by Pandaman-Ryan** [comment]
Thanks!

**Comment by AvantiShri** [comment]
FYI, I've been converting DeepLIFT to a tensorflow backend, and successfully created an example involving a sequential model trained using Keras 1.1.2 and a tensorflow backend. You can see the example here: https://github.com/kundajelab/deeplift/blob/tensorflow/examples/public/tal_gata/TAL-GATA%20simulation.ipynb

I'm not sure why 1.1.1 resulted in errors. If you do upgrade to 1.1.2, please let me know if you have trouble converting the models.
