### ISSUE TITLE
enum has no attribute

### ISSUE THREAD

**Issue by gregmcinnes** [kundajelab/deeplift#40]
I'm having trouble running the mnist and genomics examples.  The issues arise when using NonlinearMxtsMode and any specified mode.  I get attribute errors no matter what method is specified.  Any suggestions?

![image](https://user-images.githubusercontent.com/5245246/37249267-36d91696-2499-11e8-85b0-9c6c3a177911.png)

**Comment by AvantiShri** [comment]
Hi Greg, are you running an updated version of deeplift?

**Comment by gregmcinnes** [comment]
Hi Avanti,

Turns out I was using an older version of DeepLift and managed to get everything working.  I had to do a fair amount of installing and uninstalling specific versions of various packages to get it going.  You might want to include a requirements file in the future.

Thanks for you help.

Greg

**Comment by AvantiShri** [comment]
Good point, thanks.
