### ISSUE TITLE
How can I use deeplift to do motif discovery?

### ISSUE THREAD

**Issue by YichaoOU** [kundajelab/deeplift#41]
I looked at the genomic simulation examples, but I'm not sure how to use it to do motif discovery. For example, in MEME, we can just give it a fasta file and it will output some motifs. 

Thanks!
Yichao

**Comment by AvantiShri** [comment]
Hi @YichaoOU,

You're thinking of TF-MoDISco, which is a different piece of software. The manuscript isn't out yet, but I recently released the code + an example notebook publicly at https://github.com/kundajelab/tfmodisco. I'm still updating and fine-tuning the algorithm, which is partly why we haven't pushed out a manuscript yet. I would welcome your feedback on the current pre-release.
