### ISSUE TITLE
Explicit sequential model breaks connect_list_of_layers keras2compat

### ISSUE THREAD

**Issue by njwfish** [kundajelab/deeplift#46]
Running keras 2.1.6, model config saved as a .yaml file, weights as a .h5, on keras2compat branch. 

When I try to load the model, I get the error: `AttributeError: 'Input' object has no attribute 'set_inputs'` from `connect_list_of_layers`. 

I fixed this by modifying the `sequential_container_conversion` function to start at `config[1:]`, but this isn’t a great fix.

Issues stems from the fact that, if you have an explicit input layer in a sequential model then an input layer is created and appended to `converted_layers`, then it is appended again to `converted_layers` in `sequential_container_conversion`.

**Comment by AvantiShri** [comment]
Thanks for making an issue, Nic. I am actually having difficulty creating a Sequential model which, when saved, ends up with an explicit "Input" layer as the first layer `model.add(keras.layers.Input(...))` seems to throw the error `"The added layer must be an instance of class Layer"`. Would you mind sharing (here or via slack) the Keras code that went into creating the model?

Thanks,
Avanti

**Comment by njwfish** [comment]
`
from keras.layers import InputLayer
model = Sequential()
model.add(InputLayer((150, 4, 1)))
`

**Comment by AvantiShri** [comment]
Thanks Nic. Should be fixed in https://github.com/kundajelab/deeplift/pull/47
