### ISSUE TITLE
kc.prelu_conversion() fails

### ISSUE THREAD

**Issue by jisungk** [kundajelab/deeplift#55]
The Keras model conversion fails for models with a PReLU layer. It appears that the reason is that the way the alpha parameters are accessed (in the keras conversion module) is no longer compatible with the current version of Keras (2.2.0).

**Comment by AvantiShri** [comment]
Thanks for catching! I wrote a fix and modified the tests to cover PReLU conversion. Please let me know if you have any other issues.
