### ISSUE TITLE
AttributeError: 'module' object has no attribute 'max_pool_grad'

### ISSUE THREAD

**Issue by hw449** [kundajelab/deeplift#64]
After running this line:
deeplift_contribs_func = deeplift_model.get_target_contribs_func(
                             find_scores_layer_idx=find_scores_layer_idx,
                             target_layer_idx=-2)
I got the error message: AttributeError: 'module' object has no attribute 'max_pool_grad'.
I am not sure what went wrong. Could you please help me with this issue? Thanks.
The architecture of my model is:
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_1 (Conv2D)            (None, 1, 1493, 64)       2112      
_________________________________________________________________
activation_1 (Activation)    (None, 1, 1493, 64)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 1, 1493, 64)       32832     
_________________________________________________________________
activation_2 (Activation)    (None, 1, 1493, 64)       0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 1, 187, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1, 187, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 1, 187, 128)       65664     
_________________________________________________________________
activation_3 (Activation)    (None, 1, 187, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 1, 187, 128)       131200    
_________________________________________________________________
activation_4 (Activation)    (None, 1, 187, 128)       0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 1, 24, 128)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 1, 24, 128)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 1, 24, 64)         65600     
_________________________________________________________________
activation_5 (Activation)    (None, 1, 24, 64)         0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 1, 24, 64)         32832     
_________________________________________________________________
activation_6 (Activation)    (None, 1, 24, 64)         0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 1, 3, 64)          0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 1, 3, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 192)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               24704     
_________________________________________________________________
activation_7 (Activation)    (None, 128)               0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
activation_8 (Activation)    (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 130       
_________________________________________________________________
activation_9 (Activation)    (None, 2)                 0         
=================================================================
Total params: 363,330
Trainable params: 363,330
Non-trainable params: 0
_________________________________________________________________

**Comment by AvantiShri** [comment]
Hi, are you using tensorflow 1.7 or later?

**Comment by hw449** [comment]
I solved the problem by updating the tensorflow and keras to their latest version. Thanks.

**Comment by AvantiShri** [comment]
Great. Let me know if there are other issues.
