### ISSUE TITLE
Deeplift with embedding layers

### ISSUE THREAD

**Issue by gregmcinnes** [kundajelab/deeplift#66]
Is there any way to use deeplift on a model that has been trained with an embedding layer?  I use an embedding layer that is essentially just a lookup and the input is a matrix of indices.  When I try to import my model into deeplift I get the following error:

      File "/Users/gmcinnes/src/external_repos/deeplift/deeplift/conversion/kerasapi_conversion.py", line 388, in convert_model_from_saved_files
    return model_conversion_function(model_config=model_config, **kwargs)
      File "/Users/gmcinnes/src/external_repos/deeplift/deeplift/conversion/kerasapi_conversion.py", line 442, in convert_sequential_model
    layer_overrides=layer_overrides)
      File "/Users/gmcinnes/src/external_repos/deeplift/deeplift/conversion/kerasapi_conversion.py", line 475, in sequential_container_conversion
    layer_config["class_name"])
      File "/Users/gmcinnes/src/external_repos/deeplift/deeplift/conversion/kerasapi_conversion.py", line 327, in layer_name_to_conversion_function
    return name_dict[layer_name.lower()]
    KeyError: u'embedding'

Is it possible to use the model I have or will I have to find some workaround?

Thanks

**Comment by AvantiShri** [comment]
Hi Greg,

I'd suggest two options:

(1) The advantage of using the DeepLIFT implementation in this repo is that it supports the RevealCancel rule, which we have found to be beneficial in some situations. However, the downside is that not all layers are supported, as you have discovered. If you are not attached to the RevealCancel rule, you can use the DeepLIFT implementation in the [DeepExplain](https://github.com/marcoancona/DeepExplain) repository, or the [DeepSHAP](https://github.com/slundberg/shap#deep-learning-example-with-deepexplainer-tensorflowkeras-models) implementation in the shap repository (DeepSHAP is an extension of DeepLIFT to deal with several operations that DeepLIFT didn't support, but it doesn't have the RevealCancel rule)

(2) If you do want to use the RevealCancel rule, and all the other layers in your architecture are supported, you can bypass the embedding layer by structuring your network to take the embeddings themselves as inputs (i.e. you have a preprocessing step where you convert your original inputs to embeddings, and then supply the embeddings as the input to the network)

**Comment by gregmcinnes** [comment]
Thanks for the quick reply.  I was hoping to use the RevealCancel rule.  Doing some preprocessing shouldn't be that big of a deal so I'll try that.

Thanks!
