### ISSUE TITLE
PR proposal: adding simple MNIST example

### ISSUE THREAD

**Issue by jisungk** [kundajelab/deeplift#7]
I thought it would be helpful to add a dead simple use case to the `master` branch -- the MNIST dataset example adapted from the `keras_1_compatability` branch! Let me know if you think this is a good idea!

**Comment by AvantiShri** [comment]
Sounds good to me! My hesitation mostly is that we don't fully understand the best reference to use for images, but as an example use case it certainly couldn't hurt. Feel free to contribute!
