### ISSUE TITLE
Error with RNNs

### ISSUE THREAD

**Issue by Labaien96** [kundajelab/deeplift#85]
I have tried to use it with RNNs and I get the following error:
`KeyError: 'lstm'`  with LSTMs, `KeyError: 'gru'`  with GRUs, `KeyError: 'simplernn'` with SimpleRNNs ...
Did anyone else experience this behavior? It is not supported for RNNs?

**Comment by AvantiShri** [comment]
Hi Jokin,

DeepLIFT does not have an implementation that supports elementwise operations. I recommend looking at DeepSHAP in the SHAP repository, which builds on the connection between the SHAP method and DeepLIFT and has support for RNNs.
